# Generated by Django 6.0 on 2025-12-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagereport',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
